FROM node:22-alpine

# Cria diretório da aplicação
WORKDIR /app

# Copia apenas arquivos de dependência para cache
COPY package*.json ./

# Instala dependências
RUN yarn install

# Copia o restante do projeto
COPY . .

EXPOSE 5173

CMD ["yarn", "dev"]