version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - APP_PORT=${APP_PORT}
    working_dir: /app
    command: go run main.go

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}
    working_dir: /app
    command: npm run dev
